Tasks V-01/F-01 are done
EmonamontE/Need_for_drive pull request #1
Opened 2021-09-21 15:34 UTC by EmonamontE

2021-09-21 20:31 UTC, chugunovns21 requested changes

2021-09-21 20:31 UTC, chugunovns21 commented on src/components/mainPage/Main_Nav/Main_Nav.jsx
> +const Main_Nav = (props) => (
Деструктуризируй пропсы сразу

2021-09-21 20:31 UTC, chugunovns21 commented on src/components/mainPage/NavMenu/NavMenu.jsx
> +  <div className="menu_container">
Чтобы не выдумывать новые названия для классов нужно использовать css modules. Прочитай про нее и примени

2021-09-21 20:31 UTC, chugunovns21 commented on src/components/mainPage/Slider/Slider.jsx
> +  const onPrevClick = () => {
Можно обойтись без фигурных скобок

2021-09-21 20:31 UTC, chugunovns21 commented on src/index.js
> -    <App />
Оставь тут App. А уже в него импортируй свои компоненты

2021-09-21 20:31 UTC, chugunovns21 commented on src/pages/mainPage/Main_Page.jsx
> +  const toggleMenu = () => setIsOpen(!isOpen);
Ну вот тут же ты правильно написал стрелочную функцию...

2021-09-21 20:31 UTC, chugunovns21 commented on src/components/mainPage/Footer/Footer.jsx
> +  <footer className="hero_section_footer">
Странное название класса. Что оно означает?

2021-09-23 07:04 UTC, EmonamontE commented on src/index.js
> -    <App />
Выполнено

2021-09-23 07:04 UTC, EmonamontE commented on src/components/mainPage/NavMenu/NavMenu.jsx
> +  <div className="menu_container">
Выполнено

2021-09-23 07:05 UTC, EmonamontE commented on src/components/mainPage/Footer/Footer.jsx
> +  <footer className="hero_section_footer">
Проведена разъяснительная беседа

2021-09-23 07:06 UTC, EmonamontE commented on src/components/mainPage/Main_Nav/Main_Nav.jsx
> +const Main_Nav = (props) => (
Пропсы сразу деструктуризованы

2021-09-23 15:39 UTC, chugunovns21 requested changes

2021-09-23 15:39 UTC, chugunovns21 commented on src/components/mainPage/HamMenu/HamMenu.jsx
> +const HamMenu = ({toggleMenu}) => (
Опять нейминг... 
Вот я пришел поддерживать твой проект и нахожу компонент - "ветчина-меню" и что я должен из него понять?
ModalMenu - modal указатель на то, что это модальное меню

2021-09-23 15:39 UTC, chugunovns21 commented on src/components/mainPage/Header/Header.jsx
> +      <span>Need for drive</span>
Нужно ли это в span оборачивать? Если да, то зачем?

2021-09-23 15:39 UTC, chugunovns21 commented on src/components/mainPage/Sidebar/Sidebar.jsx
> +);
Смотри прошлые замечания... Я тебе прямо про этот компонент писал

2021-09-23 15:39 UTC, chugunovns21 commented on src/pages/MainPage/MainPage.jsx
> +        <SidebarLite
Что за lite? Может все-таки mobile?

2021-09-23 15:39 UTC, chugunovns21 commented on src/index.js
>  reportWebVitals();
Что делает эта строчка?

2021-09-23 15:39 UTC, chugunovns21 commented on src/pages/MainPage/mainPage.module.css
> +}
Переписываешь одни и те же стили. Прочитай еще о медиазапросах

2021-09-23 15:39 UTC, chugunovns21 commented on src/components/mainPage/HamMenu/HamMenu.jsx
> +      <button className={ styles.close_button } onClick={toggleMenu}></button>
Если тэг пустой, то он закрывается так </>

2021-09-23 21:23 UTC, EmonamontE commented on src/components/mainPage/Header/Header.jsx
> +      <span>Need for drive</span>
Аргументы отсутствуют, обернул в <h3>

2021-09-23 21:24 UTC, EmonamontE commented on src/components/mainPage/HamMenu/HamMenu.jsx
> +const HamMenu = ({toggleMenu}) => (
ветчина хорошо. модал тоже хорошо. но ветчина лучше

2021-09-24 06:33 UTC, chugunovns21 requested changes

2021-09-24 06:33 UTC, chugunovns21 commented on src/components/mainPage/SidebarMobile/SidebarMobile.jsx
> +);
Вот тут надо обсудить логику

2021-09-25 15:12 UTC, chugunovns21 requested changes

2021-09-25 15:12 UTC, chugunovns21 commented on src/components/mainPage/ModalMenu/ModalMenu.jsx
> +    <div className={ styles.container }>
Ну вот и зачем ты меня расстраиваешь :(

2021-09-25 15:12 UTC, chugunovns21 commented on src/components/mainPage/Sidebar/Sidebar.jsx
> +    <nav className={ styles.sidebar }>
Может быть все-таки будем без ретурна такие компоненты писать?

2021-09-25 15:12 UTC, chugunovns21 commented on src/index.js
>  reportWebVitals();
Что делает эта функция???

2021-09-25 16:19 UTC, merged